using System;
using System.Collections.Generic;
using System.Text;

namespace SCM.DataAccessObject
{
    /// <summary>
    /// Constant values are used throughout this application.
    /// </summary>  
    /// <author>Generated by <a href="mailto:nguyenld2020@gmail.com">Nguyen Le Dinh</a></author>
    public static class Constant
    {
        public const String RBI_CORE_LOG = "RBI.Web.Log";
        // Status of access right
        public const String RIGHT_ACCESS = "1";
        public const String LIMIT_ACCESS = "0";
        // Datetime format
        public const String MMDDYYYY = "MM/dd/yyyy";
    }
}
